### ISSUE TITLE
Want to add aLeetCode POTD

### ISSUE THREAD

**Issue by naivedyam1** [Saloni6111/DSA_POTD_Hacktoberfest2024#10]
# Issue Template

## Type of Issue

Please select one:
- [ ] Bug Report
- [ ] Time Complexity Improvement
- [ ] Code Quality Improvement
- [x] POTD Question

---

## Description

**For Bugs:**
- **Expected Behavior**: What should happen?
- **Actual Behavior**: What happened instead?
- **Steps to Reproduce**: List the steps to reproduce the bug:

**For Time Complexity Improvements:**
- **Current Solution**: Describe the existing solution and its time complexity.
- **Suggested Improvement**: Explain how the time complexity can be improved and what the new complexity would be.

**For POTD Questions:**
- **Problem Title**: Peak Index in a Mountain Array
- **Link to Problem**: [Link](https://leetcode.com/problems/peak-index-in-a-mountain-array/description/)
- **Description**:You are given an integer mountain array arr of length n where the values increase to a peak element and then decrease.

Return the index of the peak element.

Your task is to solve it in O(log(n)) time complexity.

---

## Additional Information

Please provide any other information that may help us understand the issue better (e.g., screenshots, logs, code snippets).

---

Thank you for your contribution! We appreciate your help in improving the project.

**Comment by naivedyam1** [comment]
Can you assign it to me??

**Comment by Saloni6111** [comment]
> Can you assign it to me??

done!
