### ISSUE TITLE
check for armstrong number

### ISSUE THREAD

**Issue by Aditya-K477** [Saloni6111/DSA_POTD_Hacktoberfest2024#16]
Problem Title:Check for Armstrong Number

Description:
Take a number as input as user. Check that it is armstrong or not

Example 1:

Input: num= 153
Output: IT IS AN ARMSTRONG NUMBER
Explanation: as the number as input 153 
The sum of cubes of digit should be equal to the number 1^3+5^3+3^3=153

**Comment by Aditya-K477** [comment]
@Saloni6111 can you please assign me this issue and add the hactoberfest lable

**Comment by Saloni6111** [comment]
> @Saloni6111 can you please assign me this issue and add the hactoberfest lable

add description as mentioned in pinned issue!

**Comment by Aditya-K477** [comment]
@Saloni6111 done now can you assign me this issue and add the lable

**Comment by Himanshur-debug** [comment]
@Saloni6111 Is this issue still open?
Can I be assigned this issue under hacktoberfest label ?
And Can you please guide me a bit, as GFG problems and other problems are not available in the issues section and I did one for POTD for 3rd.

**Comment by Saloni6111** [comment]
> @Saloni6111 done now can you assign me this issue and add the lable

done!

**Comment by Mustafa1765** [comment]
@Saloni6111 can you please assign me this issue and add the hactoberfest lable
