### ISSUE TITLE
calculator in python

### ISSUE THREAD

**Issue by Aditya-K477** [Saloni6111/DSA_POTD_Hacktoberfest2024#17]
Problem Title: Calculator in python

Description:
Create a calculator in python 
Take input from the user and choice 
Do not use eval function

Example 1:

Input: num1=3
num2=5
Choice "addition"

Output: the sum of the number is:8
Explanation: it takes the choice from the user

**Comment by Aditya-K477** [comment]
@Saloni6111 can you please assign me this issue and add the hactoberfest lable

**Comment by Saloni6111** [comment]
> @Saloni6111 can you please assign me this issue and add the hactoberfest lable

add problem description as mentioned in pinned issue!

**Comment by Aditya-K477** [comment]
@Saloni6111 I've added the description no6can you assign me this issue

**Comment by Saloni6111** [comment]
> @Saloni6111 I've added the description now can you assign me this issue and add the lable

Sure!

**Comment by aamishbinnaeem** [comment]
As the issue has not been closed yet. Can I work on this problem?
