### ISSUE TITLE
Adding GFG Problem 3rd,Oct

### ISSUE THREAD

**Issue by Himanshur-debug** [Saloni6111/DSA_POTD_Hacktoberfest2024#21]
# Majority Vote (GFG)

## Type of Issue

- [x] POTD Question

---

- **Problem Title**: Majority Vote.
- **Link to Problem**: [link](https://www.geeksforgeeks.org/problems/majority-vote/1)
- **Description**: The problem is to find candidates in an array nums[] that appear more than one-third of the time, or return -1 if no such candidate exists.

**Comment by Saloni6111** [comment]
merged!
