### ISSUE TITLE
Leetcode: Palindrome Number

### ISSUE THREAD

**Issue by Saloni6111** [Saloni6111/DSA_POTD_Hacktoberfest2024#26]
##  Problem Of The Day (POTD)

**Problem Title**: Palindrome Number
**Link to Problem**: [url](https://leetcode.com/problems/palindrome-number)

**Description**: 

Given an integer x, return true if x is a palindrome, and false otherwise.

Example 1:

> Input: x = 121
> Output: true
> Explanation: 121 reads as 121 from left to right and from right to left.

Example 2:

> Input: x = -121
> Output: false
> Explanation: From left to right, it reads -121. From right to left, it becomes 121-. Therefore it is not a palindrome.

Example 3:
> Input: x = 10
> Output: false
> Explanation: Reads 01 from right to left. Therefore it is not a palindrome.

 

Constraints:
- -231 <= x <= 231 - 1

Follow up: Could you solve it without converting the integer to a string?

---

Thank you for your contribution! We appreciate your help in improving the project.

**Comment by DevendraJaiswal074** [comment]
Hii @Saloni6111 
I'd love the opportunity to tackle this issue, Could you assign to me?

**Comment by Saloni6111** [comment]
merged!
