### ISSUE TITLE
Leetcode Daily Problem - Divide Players into Teams of Equal Skill

### ISSUE THREAD

**Issue by AAbhijithA** [Saloni6111/DSA_POTD_Hacktoberfest2024#31]
# Daily Problem (Divide Players into Teams of Equal Skill)

## Type of Issue

Please select one:
- [ ] Bug Report
- [ ] Time Complexity Improvement
- [ ] Code Quality Improvement
- [x] POTD Question

---

## Description

**For POTD Questions:**
- **Problem Title**: Divide Players into Teams of Equal Skill
- **Link to Problem**: [Link](https://leetcode.com/problems/divide-players-into-teams-of-equal-skill/description/?envType=daily-question&envId=2024-10-04)
- **Description**: You are given a positive integer array skill of even length n where skill[i] denotes the skill of the ith player. Divide the players into n / 2 teams of size 2 such that the total skill of each team is equal. The chemistry of a team is equal to the product of the skills of the players on that team. Return the sum of the chemistry of all the teams, or return -1 if there is no way to divide the players into teams such that the total skill of each team is equal.

---

## Additional Information

Please provide any other information that may help us understand the issue better (e.g., screenshots, logs, code snippets).

- Optimized Solution O(n) TC and O(1) SC
- Screenshot
![Screenshot_4-10-2024_10281_leetcode com](https://github.com/user-attachments/assets/00ba358e-d251-4292-91c6-e19b5c5eeb80)
- Detailed Explanation in PR

---

Thank you for your contribution! We appreciate your help in improving the project.

**Comment by AAbhijithA** [comment]
@Saloni6111 please assign this issue to me with the appropriate hacktoberfest tags! Solved this new problem efficiently 😄

**Comment by Saloni6111** [comment]
> @Saloni6111 please assign this issue to me with the appropriate hacktoberfest tags! Solved this new problem efficiently 😄

assigned! 
please add question's url on the top of your solution.

**Comment by AAbhijithA** [comment]
> > @Saloni6111 please assign this issue to me with the appropriate hacktoberfest tags! Solved this new problem efficiently 😄
> 
> assigned! 
> please add question's url on the top of your solution. 

The link is commented on top of the cpp code

**Comment by AAbhijithA** [comment]
@Saloni6111 I made a PR, please review it and if no changes are required do approve of it.
