### ISSUE TITLE
Wish to add todays leetcode potd

### ISSUE THREAD

**Issue by naivedyam1** [Saloni6111/DSA_POTD_Hacktoberfest2024#9]
# Issue Template

## Type of Issue

Please select one:
- [ ] Bug Report
- [ ] Time Complexity Improvement
- [ ] Code Quality Improvement
- [x] POTD Question

---

## Description

**For Bugs:**
- **Expected Behavior**: What should happen?
- **Actual Behavior**: What happened instead?
- **Steps to Reproduce**: List the steps to reproduce the bug:

**For Time Complexity Improvements:**
- **Current Solution**: Describe the existing solution and its time complexity.
- **Suggested Improvement**: Explain how the time complexity can be improved and what the new complexity would be.

**For POTD Questions:**
- **Problem Title**: Provide the title of the LeetCode Problem of the Day.
- **Link to Problem**: [Insert link to the problem](url)
- **Description**: Briefly describe the problem.

---

## Additional Information

Please provide any other information that may help us understand the issue better (e.g., screenshots, logs, code snippets).

---

Thank you for your contribution! We appreciate your help in improving the project.

**Comment by Saloni6111** [comment]
@naivedyam1 today's leetcode problem is already added in code you can try another one & edit the issue template here with your problem link & description.
